# Parte 1

**Tarefas 1 a 4**

Esta primeira parte do trabalho tem dois objetivos principais. O primeiro é verificar alguns parâmetros do hardware e do software utilizado e o segundo é que os estudantes preparem e se familiarizar com o ambiente do PostgreSQL.

Configuração inicial:

In [95]:
# Conectar ao banco de dados PostgreSQL
import psycopg2
import pandas as pd

config = {
    'dbname': 'icomp',
    'user': 'icomp',
    'password': 'icomp123',
    'host': 'localhost'
}

conn = psycopg2.connect(**config)
cur = conn.cursor()

## Tarefa 1

Identifique o sistema que será usado para os experimentos, incluindo informações sobre o hardware e o Sistema Operacional utilizado. Sobre o tipo de processador, quantidade de memória RAM, tamanho do disco. Devem ser também apresentadas informações sobre as caches existentes.  Sobre o Sistema Operacional, que devem ser Linux, incluir informações sobre qual a distribuição usada, versão do sistema, versão do Kernel, etc.

**O que entregar**: As informações pedidas devem ser apresentadas no jupyter notebook

In [8]:
# O comando abaixo nos informa sobre informações de processador
# Além disso, ele também apresenta algumas informações sobre as caches existentes na seção "Caches"
!lscpu

Architecture:                x86_64
  CPU op-mode(s):            32-bit, 64-bit
  Address sizes:             39 bits physical, 48 bits virtual
  Byte Order:                Little Endian
CPU(s):                      12
  On-line CPU(s) list:       0-11
Vendor ID:                   GenuineIntel
  Model name:                12th Gen Intel(R) Core(TM) i5-1235U
    CPU family:              6
    Model:                   154
    Thread(s) per core:      2
    Core(s) per socket:      10
    Socket(s):               1
    Stepping:                4
    CPU(s) scaling MHz:      73%
    CPU max MHz:             1300.0000
    CPU min MHz:             400.0000
    BogoMIPS:                4992.00
    Flags:                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pg
                             e mca cmov pat pse36 clflush dts acpi mmx fxsr sse
                             sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm cons
                             tant_tsc art arch_perfmon pebs bts rep_good nopl xt
                             opology nonstop_tsc cpuid aperfmperf tsc_known_freq
                              pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm
                             2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2
                             x2apic movbe popcnt tsc_deadline_timer aes xsave av
                             x f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault
                              epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow
                             flexpriority ept vpid ept_ad fsgsbase tsc_adjust bm
                             i1 avx2 smep bmi2 erms invpcid rdseed adx smap clfl
                             ushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1
                              xsaves split_lock_detect user_shstk avx_vnni dther
                             m arat pln pts hwp hwp_notify hwp_act_window hwp_ep
                             p hwp_pkg_req hfi vnmi umip pku ospke waitpkg gfni
                             vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_cle
                             ar serialize arch_lbr ibt flush_l1d arch_capabiliti
                             es
Virtualization features:
  Virtualization:            VT-x
Caches (sum of all):
  L1d:                       352 KiB (10 instances)
  L1i:                       576 KiB (10 instances)
  L2:                        6.5 MiB (4 instances)
  L3:                        12 MiB (1 instance)
NUMA:
  NUMA node(s):              1
  NUMA node0 CPU(s):         0-11
Vulnerabilities:
  Gather data sampling:      Not affected
  Ghostwrite:                Not affected
  Indirect target selection: Not affected
  Itlb multihit:             Not affected
  L1tf:                      Not affected
  Mds:                       Not affected
  Meltdown:                  Not affected
  Mmio stale data:           Not affected
  Reg file data sampling:    Mitigation; Clear Register File
  Retbleed:                  Not affected
  Spec rstack overflow:      Not affected
  Spec store bypass:         Mitigation; Speculative Store Bypass disabled via p
                             rctl
  Spectre v1:                Mitigation; usercopy/swapgs barriers and __user poi
                             nter sanitization
  Spectre v2:                Mitigation; Enhanced / Automatic IBRS; IBPB conditi
                             onal; PBRSB-eIBRS SW sequence; BHI BHI_DIS_S
  Srbds:                     Not affected
  Tsa:                       Not affected
  Tsx async abort:           Not affected
  Vmscape:                   Mitigation; IBPB before exit to userspace

In [9]:
# O comando abaixo nos dá informações sobre a quantidade de memória RAM e de swap 
!free -h

               total        used        free      shared  buff/cache   available
Mem:            19Gi       7.4Gi       529Mi       1.1Gi        12Gi        11Gi
Swap:          8.0Gi       504Ki       8.0Gi

In [10]:
# Aqui nós podemos visualizar o tamanho do disco
# Caso apareça "loopX", são dispositivos virtuais para finalidades diversas como pacotes linux
# porém não são dispositivos reais
!lsblk

NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0         7:0    0   2.1G  1 loop /snap/clion/393
loop1         7:1    0     4K  1 loop /snap/bare/5
loop2         7:2    0  55.5M  1 loop /snap/core18/2959
loop3         7:3    0  55.5M  1 loop /snap/core18/2976
loop4         7:4    0 104.2M  1 loop /snap/core/17247
loop5         7:5    0  63.8M  1 loop /snap/core20/2669
loop6         7:6    0  63.8M  1 loop /snap/core20/2682
loop7         7:7    0  73.9M  1 loop /snap/core22/2139
loop8         7:8    0 250.1M  1 loop /snap/firefox/7298
loop10        7:10   0 114.1M  1 loop /snap/discord/258
loop11        7:11   0   193M  1 loop /snap/gaming-graphics-core22/184
loop12        7:12   0 250.1M  1 loop /snap/firefox/7355
loop13        7:13   0  18.5M  1 loop /snap/firmware-updater/210
loop14        7:14   0 349.7M  1 loop /snap/gnome-3-38-2004/143
loop15        7:15   0  91.7M  1 loop /snap/gtk-common-themes/1535
loop16        7:16   0 516.2M  1 loop /snap/gnome-42-2204/226
loop17        7:17   0  10.8M  1 loop /snap/snap-store/1270
loop18        7:18   0 189.6M  1 loop /snap/spotify/88
loop19        7:19   0  50.9M  1 loop /snap/snapd/25577
loop20        7:20   0   576K  1 loop /snap/snapd-desktop-integration/315
loop21        7:21   0 238.8M  1 loop /snap/steam/218
loop22        7:22   0 196.6M  1 loop /snap/spotify/89
loop23        7:23   0 117.5M  1 loop /snap/discord/260
nvme0n1     259:0    0 238.5G  0 disk
├─nvme0n1p1 259:1    0     1G  0 part /boot/efi
└─nvme0n1p2 259:2    0 237.4G  0 part /

In [11]:
# Aqui podemos ver o Sistema Operacional, a distro, e a versão do sistema
!cat /etc/os-release

PRETTY_NAME="Ubuntu 24.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.3 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

In [12]:
# Esse comando serve para visualizarmos a versão do kernel do sistema
!uname -r

6.14.0-35-generic

## Tarefa 2

a) Identifique o modelo exato do disco utilizado nos experimentos (sem uso de sudo) e, a partir da documentação técnica do fabricante (datasheet ou site oficial), registre os seguintes parâmetros: número de superfícies (se disponível), cilindros, setores por trilha (se disponível), velocidade de rotação, latência rotacional, tempos de seek médio, máximo e mínimo, tempo para a próxima trilha e taxa de transferência.

Apresente no notebook: 
O comando utilizado para obter o modelo do disco no Linux.
O modelo encontrado.
Os valores extraídos do datasheet (com a referência da fonte).

b) Utilizando o comando “stat” do Linux, verifique os parâmetros dos parâmetros de S.O. que serão utilizados para o disco. 

c) Verifique o tamanho de bloco utilizado e mostre como alterar o tamanho dos blocos

**O que entregar**: Os resultados de cada verificação devem ser preenchidas no jupyter notebook

In [15]:
# a)
# Podemos usar o comando lsblk de uma outra forma para obter o modelo do disco
!lsblk -o NAME,MODEL,TYPE

NAME        MODEL                    TYPE
loop0                                loop
loop1                                loop
loop2                                loop
loop3                                loop
loop4                                loop
loop5                                loop
loop6                                loop
loop7                                loop
loop8                                loop
loop10                               loop
loop11                               loop
loop12                               loop
loop13                               loop
loop14                               loop
loop15                               loop
loop16                               loop
loop17                               loop
loop18                               loop
loop19                               loop
loop20                               loop
loop21                               loop
loop22                               loop
loop23                               loop
nvme0n1     SAMSUNG MZVLQ256HBJD-00B disk
├─nvme0n1p1                          part
└─nvme0n1p2                          part

Exemplo de disco para pesquisar: Seagate Barracuda ST31000524AS

Referências: 
- https://www.seagate.com/docs/pdf/en-GB/datasheet/disc/barracuda-7200-12-ds1668-6-1101gb.pdf [1]
- https://www.comx-computers.co.za/ST31000524AS-specifications-42961.htm [2]
- https://www.seagate.com/staticfiles/support/docs/100636864b.pdf [3]

Parâmetros encontrados:
- número de superfícies (se disponível): 2 [3]
- cilindros: 16383 [3]
- setores por trilha (se disponível): 63 [3]
- velocidade de rotação: 7200 RPM [1]
- latência rotacional: 4.17 ms [1]
- tempos de seek médio, máximo e mínimo: Apenas foi encontrado random seek read (<8.5ms) e random seek write (<9.5ms) [2] 
- tempo para a próxima trilha: <1.0ms para read e <1.2ms para write [3]
- taxa de transferência: 600 MB/s [1]

In [19]:
# b) Segue a execução do comando stat
!stat -f /

  File: "/"
    ID: 6463411f5c535f91 Namelen: 255     Type: ext2/ext3
Block size: 4096       Fundamental block size: 4096
Blocks: Total: 60984407   Free: 33547428   Available: 30431384
Inodes: Total: 15564800   Free: 14820427

c) Caso quisesse fazer a alteração do tamanho de bloco, poderia fazer o comando `sudo mkfs.ext4 -b 8192 /dev/sdb1` por exemplo, em que ele criaria um novo sistema de arquivos com tamanho de bloco 8192 e já formataria o dispositivo /dev/sdb1 para isso. Mas não recomendamos a execucação desse comando para não perder informações ou esbagaçar com o computador

## Tarefa 3

Essa tarefa consiste na criação de banco de dados e povoamento destas tabelas com dados sintéticos.  Para a definição do esquema das tabelas e os dados a serem carregados usaremos a especificação e os utilitários fornecidos pelos Benchmark TPC-H (http://www.tpc.org/tpch/). 	

Para geração do BD no PostgreSQL, siga as instruções disponíveis em:

https://github.com/foliveirafilho/tpch-pgsql

**O que entregar**: Devem ser apresentadas as saídas da execução dos scripts de geração.

In [70]:
# Baixando os dados sintéticos
!wget -q https://github.com/electrum/tpch-dbgen/archive/32f1c1b92d1664dba542e927d23d86ffa57aa253.zip -O tpch-dbgen.zip
!unzip -q tpch-dbgen.zip && mv tpch-dbgen-32f1c1b92d1664dba542e927d23d86ffa57aa253 tpch-dbgen && rm tpch-dbgen.zip

# Baixando o repositório que possui os scripts de criação das tabelas
!git clone --no-verbose https://github.com/foliveirafilho/tpch-pgsql.git
!mv tpch-dbgen tpch-pgsql/

# Preparando para execução dos scripts
!mkdir -p data
!chmod -R a+rwx tpch-pgsql/tpch-dbgen
!chmod g+s tpch-pgsql/tpch-dbgen

Cloning into 'tpch-pgsql'...
remote: Enumerating objects: 164, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 164 (delta 0), reused 0 (delta 0), pack-reused 160 (from 1)
Receiving objects: 100% (164/164), 774.38 KiB | 957.00 KiB/s, done.
Resolving deltas: 100% (69/69), done.

In [72]:
# Rodando a fase "prepare" uma vez, mas irá dar erro. Por algum motivo desconhecido, o arquivo nation.tbl não é criado 
# com as permissões necessárias da primeira vez, por isso damos chmod novamente 
!cd tpch-pgsql && umask 0000 && python3 tpch_pgsql.py prepare -U icomp -W icomp123 -d icomp -i ../data
!chmod -R +777 tpch-pgsql/tpch-dbgen/*

make: Nothing to be done for 'all'.
built dbgen from source
TPC-H Population Generator (Version 2.14.0)
Copyright Transaction Processing Performance Council 1994 - 2010
Generating data for suppliers table
Preloading text ...                                                                                                                                                                                                                                                                                                              1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 91010101010101010
done.
Generating data for customers tabledone.
Generating data for orders/lineitem tablesdone.
Generating data for part/partsupplier tablesdone.
Generating data for nation tableOpen failed for ./nation.tbl at bm_utils.c:417
could not generate data files.

In [73]:
# Dessa vez estamos rodando a fase "prepare" pra valer
!cd tpch-pgsql && umask 0000 && python3 tpch_pgsql.py prepare -U icomp -W icomp123 -d icomp -i ../data

make: Nothing to be done for 'all'.
built dbgen from source
TPC-H Population Generator (Version 2.14.0)
Copyright Transaction Processing Performance Council 1994 - 2010
Generating data for suppliers table
Preloading text ...                                                                                                                                                                                                                                                                                                              1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 91010101010101010
done.
Generating data for customers tabledone.
Generating data for orders/lineitem tablesdone.
Generating data for part/partsupplier tablesdone.
Generating data for nation tabledone.
Generating data for region tabledone.
generated data for the load phase
TPC-H Population Generator (Version 2.14.0)
Copyright Transaction Processing Performance Council 1994 - 2010
Generating update pair #1 for orders/lineitem tables
Preloading text ...                                                                                                                                                                                                                                                                                                              1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 91010101010101010
done.
Generating update pair #2 for orders/lineitem tablesdone.
Generating update pair #3 for orders/lineitem tablesdone.
generated data for the update phase
generated data for the delete phase
created data files in ../data
created query files in ./query_root

In [ ]:
# Executando a fase de "load" que popula de fato o banco de dados
!cd tpch-pgsql && umask 0000 && python3 tpch_pgsql.py load -U icomp -W icomp123 -d icomp -i ../data

dropped existing tables
cleaned database icomp
done creating schemas
done loading data to tables
done creating indexes and foreign keys
============================================================
=========================== Load ===========================
============================================================
create_schema: : 0:00:00.051387
load_data: 0:00:37.781854
index_tables: 0:00:27.964895
============================================================
======================= End Results ========================
============================================================

## Tarefa 4 – Execução de Consultas

A segunda tarefa deste trabalho consiste em executar e analisar um conjunto de consultas analíticas do benchmark TPC-H sobre o banco de dados gerado na Tarefa 3, observando o comportamento do PostgreSQL em diferentes tipos de operações (filtros, junções, agregações e ordenações). O objetivo é compreender como o otimizador escolhe planos de execução e medir o tempo de resposta de consultas típicas de um sistema de apoio à decisão.

O TPC-H define 22 consultas padronizadas (Q1 a Q22), mas para este trabalho será utilizado um subconjunto representativo composto por 8 consultas que abrangem diferentes padrões de acesso.

Consultas a executar: Q1, Q3, Q5, Q6, Q7, Q9, Q10 e Q12. As consultas originais podem ser obtidos no repositório oficial do benchmark. Essas consultas devem ser executadas no mesmo banco TPC-H criado na Tarefa 3, utilizando o PostgreSQL.

Para cada consulta:
- Execute o comando SQL completo no PostgreSQL.
- Mostre as 10 primeiras linhas do resultado (ou um trecho representativo).
- Execute o comando EXPLAIN ANALYZE antes da consulta para exibir o plano de execução e o tempo real medido O comando EXPLAIN ANALYZE mostra as etapas internas do plano escolhido pelo otimizador, o número de linhas processadas e o tempo de cada operação.
- Registre o tempo total de execução e comente brevemente o tipo de acesso observado (por exemplo, varredura sequencial, uso de índice, junções em hash, etc.).

**O que entregar**: Devem ser apresentados os resultados acima

In [109]:
def executar_consulta_sql(query, conn=conn, cur=cur):
    try:
        # Obtém os resultados da query normalmente
        cur.execute(query)

        dados = cur.fetchall()
        
        nomes_colunas = [desc[0] for desc in cur.description]

        # Executa a mesma query com o explain analyze
        cur.execute("EXPLAIN ANALYZE\n" + query)

        explain = cur.fetchall()

        if explain:
            explain = [linha[0] for linha in explain]
            explain_formatado = "\n".join(explain)
            print(explain_formatado)
        else:
            print("Falha ao obter o plano EXPLAIN ANALYZE.")

        return nomes_colunas, dados

    except (Exception, psycopg2.Error) as error:
        print(f"Erro ao interagir com o PostgreSQL: {error}")
        return None, None

In [ ]:
print("Query 1:")

query_1 = """
select
	l_returnflag,
	l_linestatus,
	sum(l_quantity) as sum_qty,
	sum(l_extendedprice) as sum_base_price,
	sum(l_extendedprice * (1 - l_discount)) as sum_disc_price,
	sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) as sum_charge,
	avg(l_quantity) as avg_qty,
	avg(l_extendedprice) as avg_price,
	avg(l_discount) as avg_disc,
	count(*) as count_order
from
	lineitem
where
	l_shipdate <= date '1998-12-01' - interval '109' day
group by
	l_returnflag,
	l_linestatus
order by
	l_returnflag,
	l_linestatus
LIMIT 10;
"""

colunas, dados = executar_consulta_sql(query_1)
df = pd.DataFrame(data=dados, columns=colunas)
df

Query 1:
Limit  (cost=230619.88..230621.84 rows=6 width=236) (actual time=4839.427..4848.246 rows=4 loops=1)
  ->  Finalize GroupAggregate  (cost=230619.88..230621.84 rows=6 width=236) (actual time=4801.224..4810.039 rows=4 loops=1)
        Group Key: l_returnflag, l_linestatus
        ->  Gather Merge  (cost=230619.88..230621.28 rows=12 width=236) (actual time=4801.136..4809.852 rows=12 loops=1)
              Workers Planned: 2
              Workers Launched: 2
              ->  Sort  (cost=229619.86..229619.87 rows=6 width=236) (actual time=4771.520..4771.523 rows=4 loops=3)
                    Sort Key: l_returnflag, l_linestatus
                    Sort Method: quicksort  Memory: 27kB
                    Worker 0:  Sort Method: quicksort  Memory: 27kB
                    Worker 1:  Sort Method: quicksort  Memory: 27kB
                    ->  Partial HashAggregate  (cost=229619.64..229619.78 rows=6 width=236) (actual time=4771.435..4771.448 rows=4 loops=3)
                          Group Key: l_returnflag, l_linestatus
                          Batches: 1  Memory Usage: 24kB
                          Worker 0:  Batches: 1  Memory Usage: 24kB
                          Worker 1:  Batches: 1  Memory Usage: 24kB
                          ->  Parallel Seq Scan on lineitem  (cost=0.00..143855.12 rows=2450415 width=25) (actual time=19.176..744.954 rows=1959129 loops=3)
                                Filter: (l_shipdate <= '1998-08-14 00:00:00'::timestamp without time zone)
                                Rows Removed by Filter: 41276
Planning Time: 0.451 ms
JIT:
  Functions: 28
  Options: Inlining false, Optimization false, Expressions true, Deforming true
  Timing: Generation 7.910 ms, Inlining 0.000 ms, Optimization 4.071 ms, Emission 91.622 ms, Total 103.602 ms
Execution Time: 4852.054 ms

,l_returnflag,l_linestatus,sum_qty,sum_base_price,sum_disc_price,sum_charge,avg_qty,avg_price,avg_disc,count_order
0,A,F,37734107,56586554400.73,53758257134.8700,55909065222.827692,25.5220058532573370,38273.129734621672,0.04998529583839761162,1478493
1,N,F,991417,1487504710.38,1413082168.0541,1469649223.194375,25.5164719205229835,38284.467760848304,0.05009342667421629691,38854
2,N,O,73477184,110203196620.51,104694637634.7276,108886216147.035144,25.5025418484359311,38249.446707783051,0.04999604327545987378,2881171
3,R,F,37719753,56568041380.90,53741292684.6040,55889619119.831932,25.5057936126907707,38250.854626099657,0.05000940583012705647,1478870

In [111]:
print("Query 3:")

query_3 = """
select
	l_orderkey,
	sum(l_extendedprice * (1 - l_discount)) as revenue,
	o_orderdate,
	o_shippriority
from
	customer,
	orders,
	lineitem
where
	c_mktsegment = 'HOUSEHOLD'
	and c_custkey = o_custkey
	and l_orderkey = o_orderkey
	and o_orderdate < date '1995-03-09'
	and l_shipdate > date '1995-03-09'
group by
	l_orderkey,
	o_orderdate,
	o_shippriority
order by
	revenue desc,
	o_orderdate
LIMIT 10;
"""

colunas, dados = executar_consulta_sql(query_3)
df = pd.DataFrame(data=dados, columns=colunas)
df

Query 3:
Limit  (cost=196803.46..196803.48 rows=10 width=44) (actual time=1027.828..1042.620 rows=10 loops=1)
  ->  Sort  (cost=196803.46..197608.17 rows=321886 width=44) (actual time=993.893..1008.682 rows=10 loops=1)
        Sort Key: (sum((lineitem.l_extendedprice * ('1'::numeric - lineitem.l_discount)))) DESC, orders.o_orderdate
        Sort Method: top-N heapsort  Memory: 26kB
        ->  Finalize GroupAggregate  (cost=147486.18..189847.62 rows=321886 width=44) (actual time=957.044..1002.932 rows=11424 loops=1)
              Group Key: lineitem.l_orderkey, orders.o_orderdate, orders.o_shippriority
              ->  Gather Merge  (cost=147486.18..182471.07 rows=268238 width=44) (actual time=957.016..988.889 rows=11424 loops=1)
                    Workers Planned: 2
                    Workers Launched: 2
                    ->  Partial GroupAggregate  (cost=146486.15..150509.72 rows=134119 width=44) (actual time=914.569..928.341 rows=3808 loops=3)
                          Group Key: lineitem.l_orderkey, orders.o_orderdate, orders.o_shippriority
                          ->  Sort  (cost=146486.15..146821.45 rows=134119 width=24) (actual time=914.465..915.428 rows=10101 loops=3)
                                Sort Key: lineitem.l_orderkey, orders.o_orderdate, orders.o_shippriority
                                Sort Method: quicksort  Memory: 1022kB
                                Worker 0:  Sort Method: quicksort  Memory: 1005kB
                                Worker 1:  Sort Method: quicksort  Memory: 534kB
                                ->  Nested Loop  (cost=4539.39..132312.80 rows=134119 width=24) (actual time=74.614..906.407 rows=10101 loops=3)
                                      ->  Parallel Hash Join  (cost=4538.96..39289.17 rows=61651 width=12) (actual time=74.353..356.486 rows=48129 loops=3)
                                            Hash Cond: (orders.o_custkey = customer.c_custkey)
                                            ->  Parallel Seq Scan on orders  (cost=0.00..33948.50 rows=305404 width=16) (actual time=19.956..176.060 rows=241170 loops=3)
                                                  Filter: (o_orderdate < '1995-03-09'::date)
                                                  Rows Removed by Filter: 258830
                                            ->  Parallel Hash  (cost=4381.25..4381.25 rows=12617 width=4) (actual time=53.922..53.924 rows=10063 loops=3)
                                                  Buckets: 32768  Batches: 1  Memory Usage: 1472kB
                                                  ->  Parallel Seq Scan on customer  (cost=0.00..4381.25 rows=12617 width=4) (actual time=11.752..27.912 rows=10063 loops=3)
                                                        Filter: (c_mktsegment = 'HOUSEHOLD'::bpchar)
                                                        Rows Removed by Filter: 39937
                                      ->  Index Scan using idx_lineitem_orderkey on lineitem  (cost=0.43..1.42 rows=9 width=16) (actual time=0.011..0.011 rows=0 loops=144386)
                                            Index Cond: (l_orderkey = orders.o_orderkey)
                                            Filter: (l_shipdate > '1995-03-09'::date)
                                            Rows Removed by Filter: 4
Planning Time: 1.001 ms
JIT:
  Functions: 82
  Options: Inlining false, Optimization false, Expressions true, Deforming true
  Timing: Generation 12.028 ms, Inlining 0.000 ms, Optimization 6.132 ms, Emission 122.851 ms, Total 141.011 ms
Execution Time: 1045.530 ms

   l_orderkey      revenue o_orderdate  o_shippriority
0     2845094  433962.5553  1995-03-06               0
1     2113221  400959.3634  1995-02-19               0
2     1902471  400497.3847  1995-03-01               0
3     2184195  396839.1463  1995-03-04               0
4      377827  391356.6942  1995-03-08               0
5      519556  390030.5160  1995-02-15               0
6     2529826  387365.1560  1995-02-17               0
7     5329575  374659.8572  1995-03-07               0
8     3323684  370249.1932  1995-03-05               0
9     2906022  370116.1556  1995-02-27               0

In [ ]:
print("Query 5:")

query_5 = """
select
	n_name,
	sum(l_extendedprice * (1 - l_discount)) as revenue
from
	customer,
	orders,
	lineitem,
	supplier,
	nation,
	region
where
	c_custkey = o_custkey
	and l_orderkey = o_orderkey
	and l_suppkey = s_suppkey
	and c_nationkey = s_nationkey
	and s_nationkey = n_nationkey
	and n_regionkey = r_regionkey
	and r_name = 'AFRICA'
	and o_orderdate >= date '1993-01-01'
	and o_orderdate < date '1993-01-01' + interval '1' year
group by
	n_name
order by
	revenue desc
LIMIT 10;
"""

colunas, dados = executar_consulta_sql(query_5)
df = pd.DataFrame(data=dados, columns=colunas)
df

Query 5:
Limit  (cost=83916.23..83916.25 rows=10 width=136) (actual time=1061.101..1080.144 rows=5 loops=1)
  ->  Sort  (cost=83916.23..83916.29 rows=25 width=136) (actual time=1061.098..1080.140 rows=5 loops=1)
        Sort Key: (sum((lineitem.l_extendedprice * ('1'::numeric - lineitem.l_discount)))) DESC
        Sort Method: quicksort  Memory: 25kB
        ->  Finalize GroupAggregate  (cost=83870.40..83915.69 rows=25 width=136) (actual time=1059.835..1080.123 rows=5 loops=1)
              Group Key: nation.n_name
              ->  Gather Merge  (cost=83870.40..83915.00 rows=50 width=136) (actual time=1059.381..1080.085 rows=15 loops=1)
                    Workers Planned: 2
                    Workers Launched: 2
                    ->  Partial GroupAggregate  (cost=82870.38..82909.20 rows=25 width=136) (actual time=1022.550..1024.236 rows=5 loops=3)
                          Group Key: nation.n_name
                          ->  Sort  (cost=82870.38..82878.08 rows=3081 width=116) (actual time=1022.076..1022.316 rows=2409 loops=3)
                                Sort Key: nation.n_name
                                Sort Method: quicksort  Memory: 256kB
                                Worker 0:  Sort Method: quicksort  Memory: 170kB
                                Worker 1:  Sort Method: quicksort  Memory: 267kB
                                ->  Hash Join  (cost=476.32..82691.85 rows=3081 width=116) (actual time=7.568..1018.125 rows=2409 loops=3)
                                      Hash Cond: ((lineitem.l_suppkey = supplier.s_suppkey) AND (customer.c_nationkey = supplier.s_nationkey))
                                      ->  Nested Loop  (cost=3.32..81814.44 rows=77029 width=128) (actual time=0.456..974.137 rows=60488 loops=3)
                                            ->  Nested Loop  (cost=2.89..24312.84 rows=19254 width=116) (actual time=0.364..636.299 rows=15093 loops=3)
                                                  ->  Hash Join  (cost=2.46..4586.84 rows=12500 width=116) (actual time=0.242..36.630 rows=9921 loops=3)
                                                        Hash Cond: (customer.c_nationkey = nation.n_nationkey)
                                                        ->  Parallel Seq Scan on customer  (cost=0.00..4225.00 rows=62500 width=8) (actual time=0.038..17.943 rows=50000 loops=3)
                                                        ->  Hash  (cost=2.40..2.40 rows=5 width=108) (actual time=0.122..0.126 rows=5 loops=3)
                                                              Buckets: 1024  Batches: 1  Memory Usage: 9kB
                                                              ->  Hash Join  (cost=1.07..2.40 rows=5 width=108) (actual time=0.101..0.115 rows=5 loops=3)
                                                                    Hash Cond: (nation.n_regionkey = region.r_regionkey)
                                                                    ->  Seq Scan on nation  (cost=0.00..1.25 rows=25 width=112) (actual time=0.025..0.028 rows=25 loops=3)
                                                                    ->  Hash  (cost=1.06..1.06 rows=1 width=4) (actual time=0.040..0.041 rows=1 loops=3)
                                                                          Buckets: 1024  Batches: 1  Memory Usage: 9kB
                                                                          ->  Seq Scan on region  (cost=0.00..1.06 rows=1 width=4) (actual time=0.017..0.021 rows=1 loops=3)
                                                                                Filter: (r_name = 'AFRICA'::bpchar)
                                                                                Rows Removed by Filter: 4
                                                  ->  Index Scan using idx_orders_custkey on orders  (cost=0.43..1.55 rows=3 width=8) (actual time=0.025..0.059 rows=2 loops=29764)
                                                        Index Cond: (o_custkey = customer.c_custkey)
                                                        Filter: ((o_orderdate >= '1993-01-01'::date) AND (o_orderdate < '1994-01-01 00:00:00'::timestamp without time zone))
                                                        Rows Removed by Filter: 9
                                            ->  Index Scan using idx_lineitem_orderkey on lineitem  (cost=0.43..2.83 rows=16 width=20) (actual time=0.019..0.020 rows=4 loops=45280)
                                                  Index Cond: (l_orderkey = orders.o_orderkey)
                                      ->  Hash  (cost=323.00..323.00 rows=10000 width=8) (actual time=6.445..6.446 rows=10000 loops=3)
                                            Buckets: 16384  Batches: 1  Memory Usage: 519kB
                                            ->  Seq Scan on supplier  (cost=0.00..323.00 rows=10000 width=8) (actual time=0.025..3.072 rows=10000 loops=3)
Planning Time: 6.666 ms
Execution Time: 1080.351 ms

                      n_name        revenue
0  MOZAMBIQUE                 56599200.5922
1  ALGERIA                    53712346.4652
2  ETHIOPIA                   52353884.4356
3  MOROCCO                    49958146.4192
4  KENYA                      48330222.5607

In [113]:
print("Query 6:")

query_6 = """
select
	sum(l_extendedprice * l_discount) as revenue
from
	lineitem
where
	l_shipdate >= date '1993-01-01'
	and l_shipdate < date '1993-01-01' + interval '1' year
	and l_discount between 0.04 - 0.01 and 0.04 + 0.01
	and l_quantity < 25
LIMIT 10;
"""

colunas, dados = executar_consulta_sql(query_6)
df = pd.DataFrame(data=dados, columns=colunas)
df

Query 6:
Limit  (cost=170111.24..170111.25 rows=1 width=32) (actual time=662.826..672.689 rows=1 loops=1)
  ->  Finalize Aggregate  (cost=170111.24..170111.25 rows=1 width=32) (actual time=650.879..660.740 rows=1 loops=1)
        ->  Gather  (cost=170111.02..170111.23 rows=2 width=32) (actual time=650.543..660.677 rows=3 loops=1)
              Workers Planned: 2
              Workers Launched: 2
              ->  Partial Aggregate  (cost=169111.02..169111.03 rows=1 width=32) (actual time=625.220..625.222 rows=1 loops=3)
                    ->  Parallel Seq Scan on lineitem  (cost=0.00..168859.22 rows=50360 width=12) (actual time=8.135..600.877 rows=39598 loops=3)
                          Filter: ((l_shipdate >= '1993-01-01'::date) AND (l_shipdate < '1994-01-01 00:00:00'::timestamp without time zone) AND (l_discount >= 0.03) AND (l_discount <= 0.05) AND (l_quantity < '25'::numeric))
                          Rows Removed by Filter: 1960807
Planning Time: 0.173 ms
JIT:
  Functions: 18
  Options: Inlining false, Optimization false, Expressions true, Deforming true
  Timing: Generation 2.763 ms, Inlining 0.000 ms, Optimization 1.866 ms, Emission 34.333 ms, Total 38.962 ms
Execution Time: 673.805 ms

         revenue
0  89520625.2970

In [114]:
print("Query 7:")

query_7 = """
select
	supp_nation,
	cust_nation,
	l_year,
	sum(volume) as revenue
from
	(
		select
			n1.n_name as supp_nation,
			n2.n_name as cust_nation,
			extract(year from l_shipdate) as l_year,
			l_extendedprice * (1 - l_discount) as volume
		from
			supplier,
			lineitem,
			orders,
			customer,
			nation n1,
			nation n2
		where
			s_suppkey = l_suppkey
			and o_orderkey = l_orderkey
			and c_custkey = o_custkey
			and s_nationkey = n1.n_nationkey
			and c_nationkey = n2.n_nationkey
			and (
				(n1.n_name = 'GERMANY' and n2.n_name = 'RUSSIA')
				or (n1.n_name = 'RUSSIA' and n2.n_name = 'GERMANY')
			)
			and l_shipdate between date '1995-01-01' and date '1996-12-31'
	) as shipping
group by
	supp_nation,
	cust_nation,
	l_year
order by
	supp_nation,
	cust_nation,
	l_year
LIMIT 10;
"""

colunas, dados = executar_consulta_sql(query_7)
df = pd.DataFrame(data=dados, columns=colunas)
df

Query 7:
Limit  (cost=59953.72..60218.45 rows=10 width=272) (actual time=1563.467..2884.381 rows=4 loops=1)
  ->  GroupAggregate  (cost=59953.72..222572.54 rows=6143 width=272) (actual time=1563.464..2884.374 rows=4 loops=1)
        Group Key: n1.n_name, n2.n_name, (EXTRACT(year FROM lineitem.l_shipdate))
        ->  Incremental Sort  (cost=59953.72..222388.25 rows=6143 width=252) (actual time=1562.080..2879.324 rows=5880 loops=1)
              Sort Key: n1.n_name, n2.n_name, (EXTRACT(year FROM lineitem.l_shipdate))
              Presorted Key: n1.n_name, n2.n_name
              Full-sort Groups: 2  Sort Method: quicksort  Average Memory: 31kB  Peak Memory: 31kB
              Pre-sorted Groups: 2  Sort Method: quicksort  Average Memory: 372kB  Peak Memory: 375kB
              ->  Nested Loop  (cost=5834.50..221986.28 rows=6143 width=252) (actual time=64.730..2868.012 rows=5880 loops=1)
                    Join Filter: (supplier.s_nationkey = n1.n_nationkey)
                    Rows Removed by Join Filter: 141867
                    ->  Nested Loop  (cost=5834.22..173514.06 rows=153564 width=232) (actual time=64.252..2368.989 rows=147747 loops=1)
                          ->  Nested Loop  (cost=5833.79..27676.45 rows=124848 width=216) (actual time=64.209..725.154 rows=121219 loops=1)
                                ->  Gather Merge  (cost=5833.36..7287.44 rows=12485 width=216) (actual time=64.143..72.794 rows=11986 loops=1)
                                      Workers Planned: 2
                                      Workers Launched: 2
                                      ->  Sort  (cost=4833.33..4846.34 rows=5202 width=216) (actual time=34.157..35.007 rows=3995 loops=3)
                                            Sort Key: n1.n_name, n2.n_name
                                            Sort Method: quicksort  Memory: 797kB
                                            Worker 0:  Sort Method: quicksort  Memory: 82kB
                                            Worker 1:  Sort Method: quicksort  Memory: 561kB
                                            ->  Hash Join  (cost=2.87..4512.24 rows=5202 width=216) (actual time=0.288..30.750 rows=3995 loops=3)
                                                  Hash Cond: (customer.c_nationkey = n2.n_nationkey)
                                                  ->  Parallel Seq Scan on customer  (cost=0.00..4225.00 rows=62500 width=8) (actual time=0.042..18.599 rows=50000 loops=3)
                                                  ->  Hash  (cost=2.84..2.84 rows=2 width=216) (actual time=0.104..0.108 rows=2 loops=3)
                                                        Buckets: 1024  Batches: 1  Memory Usage: 9kB
                                                        ->  Nested Loop  (cost=0.00..2.84 rows=2 width=216) (actual time=0.077..0.092 rows=2 loops=3)
                                                              Join Filter: (((n1.n_name = 'GERMANY'::bpchar) AND (n2.n_name = 'RUSSIA'::bpchar)) OR ((n1.n_name = 'RUSSIA'::bpchar) AND (n2.n_name = 'GERMANY'::bpchar)))
                                                              Rows Removed by Join Filter: 2
                                                              ->  Seq Scan on nation n1  (cost=0.00..1.38 rows=2 width=108) (actual time=0.035..0.042 rows=2 loops=3)
                                                                    Filter: ((n_name = 'GERMANY'::bpchar) OR (n_name = 'RUSSIA'::bpchar))
                                                                    Rows Removed by Filter: 23
                                                              ->  Materialize  (cost=0.00..1.39 rows=2 width=108) (actual time=0.013..0.018 rows=2 loops=6)
                                                                    ->  Seq Scan on nation n2  (cost=0.00..1.38 rows=2 width=108) (actual time=0.012..0.020 rows=2 loops=3)
                                                                          Filter: ((n_name = 'RUSSIA'::bpchar) OR (n_name = 'GERMANY'::bpchar))
                                                                          Rows Removed by Filter: 23
                                ->  Index Scan using idx_orders_custkey on orders  (cost=0.43..1.46 rows=17 width=8) (actual time=0.008..0.051 rows=10 loops=11986)
                                      Index Cond: (o_custkey = customer.c_custkey)
                          ->  Index Scan using idx_lineitem_orderkey on lineitem  (cost=0.43..1.12 rows=5 width=24) (actual time=0.012..0.013 rows=1 loops=121219)
                                Index Cond: (l_orderkey = orders.o_orderkey)
                                Filter: ((l_shipdate >= '1995-01-01'::date) AND (l_shipdate <= '1996-12-31'::date))
                                Rows Removed by Filter: 3
                    ->  Index Scan using supplier_pkey on supplier  (cost=0.29..0.30 rows=1 width=8) (actual time=0.003..0.003 rows=1 loops=147747)
                          Index Cond: (s_suppkey = lineitem.l_suppkey)
Planning Time: 3.414 ms
Execution Time: 2884.528 ms

                 supp_nation                cust_nation l_year        revenue
0  GERMANY                    RUSSIA                      1995  52371954.6130
1  GERMANY                    RUSSIA                      1996  54200073.8307
2  RUSSIA                     GERMANY                     1995  51956583.5894
3  RUSSIA                     GERMANY                     1996  54122177.4076

In [115]:
print("Query 9:")

query_9 = """
select
	nation,
	o_year,
	sum(amount) as sum_profit
from
	(
		select
			n_name as nation,
			extract(year from o_orderdate) as o_year,
			l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount
		from
			part,
			supplier,
			lineitem,
			partsupp,
			orders,
			nation
		where
			s_suppkey = l_suppkey
			and ps_suppkey = l_suppkey
			and ps_partkey = l_partkey
			and p_partkey = l_partkey
			and o_orderkey = l_orderkey
			and s_nationkey = n_nationkey
			and p_name like '%blanched%'
	) as profit
group by
	nation,
	o_year
order by
	nation,
	o_year desc
LIMIT 10;
"""

colunas, dados = executar_consulta_sql(query_9)
df = pd.DataFrame(data=dados, columns=colunas)
df

Query 9:
Limit  (cost=29087.20..29115.31 rows=10 width=168) (actual time=432.389..777.474 rows=10 loops=1)
  ->  GroupAggregate  (cost=29087.20..198203.29 rows=60150 width=168) (actual time=432.386..777.461 rows=10 loops=1)
        Group Key: nation.n_name, (EXTRACT(year FROM orders.o_orderdate))
        ->  Incremental Sort  (cost=29087.20..193057.82 rows=242470 width=159) (actual time=429.861..748.215 rows=18835 loops=1)
              Sort Key: nation.n_name, (EXTRACT(year FROM orders.o_orderdate)) DESC
              Presorted Key: nation.n_name
              Full-sort Groups: 2  Sort Method: quicksort  Average Memory: 30kB  Peak Memory: 30kB
              Pre-sorted Groups: 2  Sort Method: quicksort  Average Memory: 1521kB  Peak Memory: 1521kB
              ->  Nested Loop  (cost=22381.40..173970.57 rows=242470 width=159) (actual time=157.573..708.781 rows=27066 loops=1)
                    ->  Nested Loop  (cost=22380.97..60575.92 rows=242470 width=131) (actual time=157.548..389.206 rows=27066 loops=1)
                          Join Filter: (supplier.s_suppkey = lineitem.l_suppkey)
                          ->  Gather Merge  (cost=22380.54..26145.20 rows=32324 width=126) (actual time=157.496..174.996 rows=3637 loops=1)
                                Workers Planned: 2
                                Workers Launched: 2
                                ->  Sort  (cost=21380.51..21414.18 rows=13468 width=126) (actual time=117.546..118.051 rows=1693 loops=3)
                                      Sort Key: nation.n_name
                                      Sort Method: quicksort  Memory: 2689kB
                                      Worker 0:  Sort Method: quicksort  Memory: 1360kB
                                      Worker 1:  Sort Method: quicksort  Memory: 723kB
                                      ->  Hash Join  (cost=449.99..20456.79 rows=13468 width=126) (actual time=6.079..99.583 rows=14620 loops=3)
                                            Hash Cond: (supplier.s_nationkey = nation.n_nationkey)
                                            ->  Hash Join  (cost=448.43..20413.88 rows=13468 width=26) (actual time=5.891..94.550 rows=14620 loops=3)
                                                  Hash Cond: (partsupp.ps_suppkey = supplier.s_suppkey)
                                                  ->  Nested Loop  (cost=0.42..19930.52 rows=13468 width=18) (actual time=0.111..79.350 rows=14620 loops=3)
                                                        ->  Parallel Seq Scan on part  (cost=0.00..5169.67 rows=3367 width=4) (actual time=0.040..27.585 rows=3655 loops=3)
                                                              Filter: ((p_name)::text ~~ '%blanched%'::text)
                                                              Rows Removed by Filter: 63012
                                                        ->  Index Scan using idx_partsupp_partkey on partsupp  (cost=0.42..4.34 rows=4 width=14) (actual time=0.011..0.013 rows=4 loops=10965)
                                                              Index Cond: (ps_partkey = part.p_partkey)
                                                  ->  Hash  (cost=323.00..323.00 rows=10000 width=8) (actual time=5.646..5.648 rows=10000 loops=3)
                                                        Buckets: 16384  Batches: 1  Memory Usage: 519kB
                                                        ->  Seq Scan on supplier  (cost=0.00..323.00 rows=10000 width=8) (actual time=0.019..2.861 rows=10000 loops=3)
                                            ->  Hash  (cost=1.25..1.25 rows=25 width=108) (actual time=0.065..0.066 rows=25 loops=3)
                                                  Buckets: 1024  Batches: 1  Memory Usage: 10kB
                                                  ->  Seq Scan on nation  (cost=0.00..1.25 rows=25 width=108) (actual time=0.036..0.042 rows=25 loops=3)
                          ->  Index Scan using idx_lineitem_part_supp on lineitem  (cost=0.43..1.05 rows=1 width=29) (actual time=0.015..0.054 rows=7 loops=3637)
                                Index Cond: ((l_partkey = partsupp.ps_partkey) AND (l_suppkey = partsupp.ps_suppkey))
                    ->  Index Scan using orders_pkey on orders  (cost=0.43..0.47 rows=1 width=8) (actual time=0.010..0.010 rows=1 loops=27066)
                          Index Cond: (o_orderkey = lineitem.l_orderkey)
Planning Time: 12.785 ms
Execution Time: 778.367 ms

                      nation o_year     sum_profit
0  ALGERIA                     1998  27119618.6798
1  ALGERIA                     1997  49297687.0004
2  ALGERIA                     1996  48067804.9811
3  ALGERIA                     1995  49013745.4082
4  ALGERIA                     1994  49600822.0138
5  ALGERIA                     1993  48145060.2616
6  ALGERIA                     1992  46714498.1826
7  ARGENTINA                   1998  27953626.0654
8  ARGENTINA                   1997  44648039.7369
9  ARGENTINA                   1996  48071265.3063

In [116]:
print("Query 10:")

query_10 = """
select
	c_custkey,
	c_name,
	sum(l_extendedprice * (1 - l_discount)) as revenue,
	c_acctbal,
	n_name,
	c_address,
	c_phone,
	c_comment
from
	customer,
	orders,
	lineitem,
	nation
where
	c_custkey = o_custkey
	and l_orderkey = o_orderkey
	and o_orderdate >= date '1994-02-01'
	and o_orderdate < date '1994-02-01' + interval '3' month
	and l_returnflag = 'R'
	and c_nationkey = n_nationkey
group by
	c_custkey,
	c_name,
	c_acctbal,
	c_phone,
	n_name,
	c_address,
	c_comment
order by
	revenue desc
LIMIT 10;
"""

colunas, dados = executar_consulta_sql(query_10)
df = pd.DataFrame(data=dados, columns=colunas)
df

Query 10:
Limit  (cost=165840.38..165840.40 rows=10 width=280) (actual time=899.799..913.567 rows=10 loops=1)
  ->  Sort  (cost=165840.38..165983.54 rows=57263 width=280) (actual time=860.839..874.604 rows=10 loops=1)
        Sort Key: (sum((lineitem.l_extendedprice * ('1'::numeric - lineitem.l_discount)))) DESC
        Sort Method: top-N heapsort  Memory: 29kB
        ->  Finalize GroupAggregate  (cost=157245.74..164602.95 rows=57263 width=280) (actual time=681.325..841.041 rows=37018 loops=1)
              Group Key: customer.c_custkey, nation.n_name
              ->  Gather Merge  (cost=157245.74..163409.96 rows=47720 width=280) (actual time=681.303..776.625 rows=37018 loops=1)
                    Workers Planned: 2
                    Workers Launched: 2
                    ->  Partial GroupAggregate  (cost=156245.71..156901.86 rows=23860 width=280) (actual time=634.787..702.155 rows=12339 loops=3)
                          Group Key: customer.c_custkey, nation.n_name
                          ->  Sort  (cost=156245.71..156305.36 rows=23860 width=260) (actual time=634.686..644.522 rows=36868 loops=3)
                                Sort Key: customer.c_custkey, nation.n_name
                                Sort Method: external merge  Disk: 8864kB
                                Worker 0:  Sort Method: external merge  Disk: 4512kB
                                Worker 1:  Sort Method: external merge  Disk: 7760kB
                                ->  Nested Loop  (cost=35810.56..151574.31 rows=23860 width=260) (actual time=161.830..574.827 rows=36868 loops=3)
                                      ->  Hash Join  (cost=35810.12..40910.52 rows=23805 width=252) (actual time=161.663..232.328 rows=18487 loops=3)
                                            Hash Cond: (customer.c_nationkey = nation.n_nationkey)
                                            ->  Parallel Hash Join  (cost=35808.56..40835.88 rows=23805 width=152) (actual time=119.296..181.403 rows=18487 loops=3)
                                                  Hash Cond: (customer.c_custkey = orders.o_custkey)
                                                  ->  Parallel Seq Scan on customer  (cost=0.00..4225.00 rows=62500 width=148) (actual time=0.051..16.207 rows=50000 loops=3)
                                                  ->  Parallel Hash  (cost=35511.00..35511.00 rows=23805 width=8) (actual time=118.839..118.840 rows=18487 loops=3)
                                                        Buckets: 65536  Batches: 1  Memory Usage: 2720kB
                                                        ->  Parallel Seq Scan on orders  (cost=0.00..35511.00 rows=23805 width=8) (actual time=0.066..108.563 rows=18487 loops=3)
                                                              Filter: ((o_orderdate >= '1994-02-01'::date) AND (o_orderdate < '1994-05-01 00:00:00'::timestamp without time zone))
                                                              Rows Removed by Filter: 481513
                                            ->  Hash  (cost=1.25..1.25 rows=25 width=108) (actual time=42.236..42.237 rows=25 loops=3)
                                                  Buckets: 1024  Batches: 1  Memory Usage: 10kB
                                                  ->  Seq Scan on nation  (cost=0.00..1.25 rows=25 width=108) (actual time=42.180..42.189 rows=25 loops=3)
                                      ->  Index Scan using idx_lineitem_orderkey on lineitem  (cost=0.43..4.61 rows=4 width=16) (actual time=0.016..0.017 rows=2 loops=55462)
                                            Index Cond: (l_orderkey = orders.o_orderkey)
                                            Filter: (l_returnflag = 'R'::bpchar)
                                            Rows Removed by Filter: 2
Planning Time: 1.615 ms
JIT:
  Functions: 103
  Options: Inlining false, Optimization false, Expressions true, Deforming true
  Timing: Generation 14.672 ms, Inlining 0.000 ms, Optimization 7.052 ms, Emission 158.797 ms, Total 180.521 ms
Execution Time: 919.674 ms

,c_custkey,c_name,revenue,c_acctbal,n_name,c_address,c_phone,c_comment
0,103780,Customer#000103780,682401.9358,7809.66,ETHIOPIA,qmCa2H3EzMUR4O65VB0fzisED8,15-355-745-3509,serve quickly across the even ideas. ironic i...
1,144526,Customer#000144526,680209.7103,1031.97,KENYA,ORUvZI4ziHHpATV1 VAxf47RGwiBUeuE0RSg,24-447-657-1591,"e along the permanent, express dolphins. depos..."
2,54826,Customer#000054826,668052.7708,1018.83,CHINA,"0qQN5BZXBDTUmndXQP,LO00e9ptdAWT3vMD",28-849-358-2535,riously above the final packages. pinto beans ...
3,53026,Customer#000053026,658612.3023,6626.67,KENYA,"8csvbatNzIZ34nhOGFG,8qhm aNyQ",24-657-445-1672,nusual excuses despite the furiously ironic de...
4,86629,Customer#000086629,654557.0038,3714.27,BRAZIL,vVKUYjrAl85Avns,12-789-964-5639,jole realms. slyly permanent pinto beans haggl...
5,18493,Customer#000018493,642821.7621,-805.58,CANADA,stNAdEXeBZ7LmvF9iOf,13-765-615-6286,as. furiously silent courts cajole slyly. even...
6,6403,Customer#000006403,640529.1986,9717.24,UNITED STATES,9eX1E4GyIXptoHrL5db b7wqVYaUB55u,34-376-305-4671,ly unusual accounts cajole slyly even platelet...
7,74638,Customer#000074638,620042.7691,-444.84,INDIA,BKaM5HHmXN2XLH7JYyCXOLWeQH,18-422-359-3587,oost slyly slyly final deposits
8,57976,Customer#000057976,609738.3193,4165.79,PERU,1SD8y3C4yaQjBDUgRw kn73J0U,27-575-438-1113,equests wake carefully after the regular pains
9,80488,Customer#000080488,609237.9659,87.48,MOROCCO,wHhF1C7Wc59q,25-682-349-5748,regular asymptotes. slyly express foxes thras...

In [117]:
print("Query 12:")

query_12 = """
select
	l_shipmode,
	sum(case
		when o_orderpriority = '1-URGENT'
			or o_orderpriority = '2-HIGH'
			then 1
		else 0
	end) as high_line_count,
	sum(case
		when o_orderpriority <> '1-URGENT'
			and o_orderpriority <> '2-HIGH'
			then 1
		else 0
	end) as low_line_count
from
	orders,
	lineitem
where
	o_orderkey = l_orderkey
	and l_shipmode in ('FOB', 'SHIP')
	and l_commitdate < l_receiptdate
	and l_shipdate < l_commitdate
	and l_receiptdate >= date '1993-01-01'
	and l_receiptdate < date '1993-01-01' + interval '1' year
group by
	l_shipmode
order by
	l_shipmode
LIMIT 10;
"""

colunas, dados = executar_consulta_sql(query_12)
df = pd.DataFrame(data=dados, columns=colunas)
df

Query 12:
Limit  (cost=210290.45..210532.51 rows=7 width=27) (actual time=1426.177..1439.176 rows=2 loops=1)
  ->  Finalize GroupAggregate  (cost=210290.45..210532.51 rows=7 width=27) (actual time=1389.411..1402.406 rows=2 loops=1)
        Group Key: lineitem.l_shipmode
        ->  Gather Merge  (cost=210290.45..210532.33 rows=14 width=27) (actual time=1385.914..1402.264 rows=6 loops=1)
              Workers Planned: 2
              Workers Launched: 2
              ->  Partial GroupAggregate  (cost=209290.43..209530.70 rows=7 width=27) (actual time=1349.559..1352.631 rows=2 loops=3)
                    Group Key: lineitem.l_shipmode
                    ->  Sort  (cost=209290.43..209320.45 rows=12010 width=27) (actual time=1346.898..1347.913 rows=10378 loops=3)
                          Sort Key: lineitem.l_shipmode
                          Sort Method: quicksort  Memory: 837kB
                          Worker 0:  Sort Method: quicksort  Memory: 1074kB
                          Worker 1:  Sort Method: quicksort  Memory: 945kB
                          ->  Parallel Hash Join  (cost=169009.34..208476.63 rows=12010 width=27) (actual time=1075.185..1339.732 rows=10378 loops=3)
                                Hash Cond: (orders.o_orderkey = lineitem.l_orderkey)
                                ->  Parallel Seq Scan on orders  (cost=0.00..32386.00 rows=625000 width=20) (actual time=0.092..113.393 rows=500000 loops=3)
                                ->  Parallel Hash  (cost=168859.22..168859.22 rows=12010 width=15) (actual time=1074.341..1074.344 rows=10378 loops=3)
                                      Buckets: 32768  Batches: 1  Memory Usage: 1760kB
                                      ->  Parallel Seq Scan on lineitem  (cost=0.00..168859.22 rows=12010 width=15) (actual time=25.521..1062.439 rows=10378 loops=3)
                                            Filter: ((l_shipmode = ANY ('{FOB,SHIP}'::bpchar[])) AND (l_commitdate < l_receiptdate) AND (l_shipdate < l_commitdate) AND (l_receiptdate >= '1993-01-01'::date) AND (l_receiptdate < '1994-01-01 00:00:00'::timestamp without time zone))
                                            Rows Removed by Filter: 1990027
Planning Time: 0.791 ms
JIT:
  Functions: 58
  Options: Inlining false, Optimization false, Expressions true, Deforming true
  Timing: Generation 9.482 ms, Inlining 0.000 ms, Optimization 5.553 ms, Emission 107.532 ms, Total 122.567 ms
Execution Time: 1443.141 ms

   l_shipmode  high_line_count  low_line_count
0  FOB                    6278            9259
1  SHIP                   6261            9335